In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)

In [6]:
B = np.random.randn(10)

In [9]:
A

array([-1.61320765, -0.46543801,  1.65337107,  1.17605308, -0.74583   ,
       -2.16391429, -1.84513144, -0.49485225, -1.23052625,  0.39560173])

In [12]:
#Binary Functions
np.add(A,B)

array([-2.14387537, -0.31050379,  1.25545592,  3.62409377, -0.08982602,
       -1.77595931, -1.91799571, -0.65113051, -1.20836052,  0.62066677])

In [13]:
np.maximum(A,B)

array([-0.53066772,  0.15493422,  1.65337107,  2.44804069,  0.65600398,
        0.38795498, -0.07286427, -0.15627827,  0.02216573,  0.39560173])

In [14]:
np.minimum(A,B)

array([-1.61320765, -0.46543801, -0.39791515,  1.17605308, -0.74583   ,
       -2.16391429, -1.84513144, -0.49485225, -1.23052625,  0.22506504])