In [2]:
import numpy as np

In [13]:
my_list1 = [1,2,3,4]

In [14]:
my_array1 = np.array(my_list1)

In [15]:
my_array1

array([1, 2, 3, 4])

In [16]:
my_list2 = [11,22,33,44]

In [17]:
my_lists = [my_list1,my_list2]

In [18]:
my_array2 = np.array(my_lists)

In [19]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [20]:
my_array2.shape

(2, 4)

In [21]:
my_array2.dtype

dtype('int64')

In [25]:
np.zeros([2,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [32]:
np.arange(4,42,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38, 40])

In [33]:
np.arange(4,42,3)

array([ 4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [38]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [39]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [40]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [41]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [42]:
2.5*arr1 - arr1

array([[ 1.5,  3. ,  4.5,  6. ],
       [12. , 13.5, 15. , 16.5]])

In [43]:
arr1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [44]:
#Indexing

In [45]:
arr = np.arange(0,11)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr[8]

8

In [48]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [49]:
arr[0:5] = 100

In [50]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr = np.arange(0,11)

In [52]:
arr_copy = arr.copy()

In [53]:
#zmiany beda wplywac na orginalna arr mimo tego ze nie odwolujemy sie do niej bezposrednio

In [54]:
slice_of_arr = arr[:6]

In [55]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [56]:
slice_of_arr[:]=99

In [57]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr_2d = np.array(([1,2,3],[10,15,20],[28,34,47]))

In [61]:
arr_2d

array([[ 1,  2,  3],
       [10, 15, 20],
       [28, 34, 47]])

In [62]:
arr_2d[0]

array([1, 2, 3])

In [63]:
arr_2d[1][2]

20

In [66]:
arr_2d[1,2]

20

In [64]:
arr_2d[:2,1:]

array([[ 2,  3],
       [15, 20]])

In [3]:
arr2d = np.zeros((5,7))

In [4]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [5]:
arr_lenght = arr2d.shape[1]

In [6]:
arr_height = arr2d.shape[0]

In [9]:
arr_lenght

7

In [14]:
for h in range(arr_height):
    arr2d[h] = h

In [11]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [12]:
for l in range(arr_lenght):
    arr2d[:,l] = l

In [15]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4.]])

In [16]:
arr2d[[1,3]]

array([[1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3.]])

In [113]:
arr2d[[1,3]][:,[2,4]]

array([[1., 1.],
       [3., 3.]])

In [114]:
#Transposition

In [17]:
arr3 = np.arange(50).reshape(10,5)

In [18]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [19]:
arr3.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [20]:
np.dot(arr3.T,arr3)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [30]:
arr3d = np.arange(50).reshape(5,5,2)

In [33]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [32]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [34]:
arr = np.array([[1,2,3],[4,5,6]])

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
arr.swapaxes(1,0)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [164]:
#Functions